package jsweet.dom;
/** <p>This type represents a DOM element's attribute as an object. In most DOM methods, you will probably directly retrieve the attribute as a string (e.g., <code>Element.getAttribute()</code>, but certain functions (e.g., <code>Element.getAttributeNode()</code>) or means of iterating give <code>Attr</code> types.</p> <div> <pre> 
  &lt;div id=&quot;interfaceDiagram&quot; style=&quot;display: inline-block; position: relative; width: 100%; padding-bottom: 11.666666666666666%; vertical-align: middle; overflow: hidden;&quot;&gt;&lt;svg style=&quot;display: inline-block; position: absolute; top: 0; left: 0;&quot; viewbox=&quot;-50 0 600 70&quot; preserveAspectRatio=&quot;xMinYMin meet&quot;&gt;&lt;a xlink:href=&quot;https://developer.mozilla.org/en-US/docs/Web/API/EventTarget&quot; target=&quot;_top&quot;&gt;&lt;rect x=&quot;1&quot; y=&quot;1&quot; width=&quot;110&quot; height=&quot;50&quot; fill=&quot;#fff&quot; stroke=&quot;#D4DDE4&quot; stroke-width=&quot;2px&quot; /&gt;&lt;text  x=&quot;56&quot; y=&quot;30&quot; font-size=&quot;12px&quot; font-family=&quot;Consolas,Monaco,Andale Mono,monospace&quot; fill=&quot;#4D4E53&quot; text-anchor=&quot;middle&quot; alignment-baseline=&quot;middle&quot;&gt;EventTarget&lt;/text&gt;&lt;/a&gt;&lt;polyline points=&quot;111,25  121,20  121,30  111,25&quot; stroke=&quot;#D4DDE4&quot; fill=&quot;none&quot;/&gt;&lt;line x1=&quot;121&quot; y1=&quot;25&quot; x2=&quot;151&quot; y2=&quot;25&quot; stroke=&quot;#D4DDE4&quot;/&gt;&lt;a xlink:href=&quot;https://developer.mozilla.org/en-US/docs/Web/API/Node&quot; target=&quot;_top&quot;&gt;&lt;rect x=&quot;151&quot; y=&quot;1&quot; width=&quot;75&quot; height=&quot;50&quot; fill=&quot;#fff&quot; stroke=&quot;#D4DDE4&quot; stroke-width=&quot;2px&quot; /&gt;&lt;text  x=&quot;188.5&quot; y=&quot;30&quot; font-size=&quot;12px&quot; font-family=&quot;Consolas,Monaco,Andale Mono,monospace&quot; fill=&quot;#4D4E53&quot; text-anchor=&quot;middle&quot; alignment-baseline=&quot;middle&quot;&gt;Node&lt;/text&gt;&lt;/a&gt;&lt;polyline points=&quot;226,25  236,20  236,30  226,25&quot; stroke=&quot;#D4DDE4&quot; fill=&quot;none&quot;/&gt;&lt;line x1=&quot;236&quot; y1=&quot;25&quot; x2=&quot;266&quot; y2=&quot;25&quot; stroke=&quot;#D4DDE4&quot;/&gt;&lt;a xlink:href=&quot;https://developer.mozilla.org/en-US/docs/Web/API/Attr&quot; target=&quot;_top&quot;&gt;&lt;rect x=&quot;266&quot; y=&quot;1&quot; width=&quot;75&quot; height=&quot;50&quot; fill=&quot;#F4F7F8&quot; stroke=&quot;#D4DDE4&quot; stroke-width=&quot;2px&quot; /&gt;&lt;text  x=&quot;303.5&quot; y=&quot;30&quot; font-size=&quot;12px&quot; font-family=&quot;Consolas,Monaco,Andale Mono,monospace&quot; fill=&quot;#4D4E53&quot; text-anchor=&quot;middle&quot; alignment-baseline=&quot;middle&quot;&gt;Attr&lt;/text&gt;&lt;/a&gt;&lt;/svg&gt;&lt;/div&gt; 
</pre> <pre> 
  a:hover text { fill: #0095DD; pointer-events: all;} 
</pre> </div> <iframe></iframe> <div> <strong>Warning:</strong> In DOM Core 1, 2 and 3, Attr inherited from Node. This is no longer the case in DOM4. In order to bring the implementation of <code>Attr</code> up to specification, work is underway to change it to no longer inherit from <code>Node</code>. You should not be using any <code>Node</code> properties or methods on <code>Attr</code> objects. Starting in Gecko 7.0 (Firefox 7.0 / Thunderbird 7.0 / SeaMonkey 2.4), the ones that are going to be removed output warning messages to the console. You should revise your code accordingly. See Deprecated properties and methods for a complete list. </div>  */
public class Attr extends Node {
    public String name;
    public Element ownerElement;
    public Boolean specified;
    public String value;
    public static Attr prototype;
    public Attr(){}
}

